package com.booking.entity.enums;

public enum EventType {
  UNIT_CREATED,
  UNIT_UPDATED,
  UNIT_DELETED,
  BOOKING_CREATED,
  BOOKING_CANCELLED,
  BOOKING_EXPIRED,
  PAYMENT_COMPLETED,
  PAYMENT_FAILED,
  CACHE_INVALIDATED
}